# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5e8c013a0853813ba87df86ec8e4d436543deb62bd624983369fffde4befc10157008324343a7a3974fccec3d6db8e745420bb978df91e78a1f01aea1ede6da

test:
  secret_key_base: 2dafa1a4f3e1ec03e0a2932be2b5e85bfb67bb8d02c8ccc4d62d74b1cad6e689f36b2d3b4038f5774ac00539a5d5ce4faffa5cbf5192b77d1896c89423ce02c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
